version: '2'

services:
  lv-client:
    build: lv-client
    depends_on:
      - lv-server
    env_file:
      - .env

  lv-db:
    build: lv-db
    env_file:
      - .env
    networks:
      - database

  lv-media:
    build: lv-media
    env_file:
      - .env
    depends_on:
      - lv-db
    networks:
      - database
    volumes:
      - ${HOST_MEDIA_DIR}:/media

  lv-proxy:
    build: lv-proxy
    env_file:
      - .env
    depends_on:
      - lv-client
      - lv-server
    ports:
      - "80:80"
    volumes:
      - ${HOST_MEDIA_DIR}:/media

  lv-server:
    build: lv-server
    env_file:
      - .env
    networks:
      - default
      - database
    depends_on:
      - lv-db
      - lv-media


networks:
  database:
    driver: bridge

