# To Run:
# docker-compose -f docker-compose.yml -f docker-compose-development.yml build
# docker-compose -f docker-compose.yml -f docker-compose-development.yml up

# Important Notes:
# - lv-server uses nodemon in "legacy mode", aka "-L". This is resource
#   intensive however required for boot2docker users (non-linux).
# - We run everything with elevated permissions, i.e. "privileged", DO NOT USE THIS IN PROD.

version: '2'

services:
  lv-client:
    build:
      dockerfile: Dockerfile-development
    volumes:
      - ./lv-client/client:/src/client
      - ./lv-client/server:/src/server
    privileged: true

  lv-client-watch:
    build:
      context: lv-client/
      dockerfile: Dockerfile-development
    command: yarn run watch
    volumes:
      - ./lv-client/client:/src/client
      - ./lv-client/server:/src/server
    privileged: true

  lv-server:
    build:
      dockerfile: Dockerfile-development
    volumes:
      - ./lv-server/server:/src/server
    privileged: true

  lv-media:
    build:
      dockerfile: Dockerfile-development
    volumes:
      - ./lv-media:/src
    privileged: true
